name = "cors"
main = "src/index.ts"
compatibility_date = "2022-11-24"

kv_namespaces = [
    { binding = "ANALYTICS", id = "8c62536bd6ad4df0ace52dc695898d7d", preview_id = "4daadfc8c22742acab5fb924892f76a9" },
]
